# Quick Start
# $ docker compose -f compose.pc.yaml up

x-config: &basic_setup
  restart: unless-stopped
  network_mode: host
  ipc: host

services:

  dds-router:
    <<: *basic_setup
    image: husarnet/dds-router:v0.4.0
    volumes:
      - ./router-config.client.yaml:/config.yaml
    command: >
      ddsrouter 
      --config-path /config.yaml 
      --debug

  rviz:
    <<: *basic_setup
    image: husarion/rviz2:galactic
    container_name: rviz
    volumes:
      - ./robot_model:/robot_model
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot.rviz:/root/.rviz2/default.rviz
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=1

