# Quick Start
# $ docker compose -f compose.rosbot.yaml up

# x-net-config:
#   - &dds-config-file "./dds-config.xml:/dds-config.xml" 
#   - &dds-config-env "FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml"

x-net-config:
  - &network_mode "service:husarnet-pc" 
  - &restart_policy "unless-stopped"

services:

  husarnet-pc:
    image: husarnet/husarnet
    ipc: shareable
    restart: *restart_policy
    volumes:
      - /var/lib/husarnet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=pc
      - JOINCODE

  dds-router:
    image: husarnet/dds-router:v0.4.0
    restart: *restart_policy
    network_mode: *network_mode
    ipc: *network_mode
    volumes:
      - ./router-config.client.yaml:/config.yaml
    command: >
      ddsrouter 
      --config-path /config.yaml 
      --debug

  rviz:
    image: husarion/rviz2:galactic
    container_name: rviz
    restart: *restart_policy
    network_mode: *network_mode
    ipc: *network_mode
    volumes:
      - ./robot_model:/robot_model
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot.rviz:/root/.rviz2/default.rviz
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=1

  navigation:
    image: husarion/navigation2:galactic
    restart: *restart_policy
    network_mode: *network_mode
    ipc: *network_mode
    volumes:
      - ./config/nav2_params.yaml:/nav2_params.yaml
    command: >
      ros2 launch nav2_bringup navigation_launch.py    
        params_file:=/nav2_params.yaml
        use_sim_time:=${USE_SIM_TIME:-False}
        
  localization-mapping:
    image: husarion/slam-toolbox:galactic
    container_name: slam-toolbox
    restart: *restart_policy
    network_mode: *network_mode
    ipc: *network_mode
    volumes:
      - ./config/slam_params.yaml:/slam_params.yaml
      - ./maps:/maps
    command: >
      ros2 launch slam_toolbox online_sync_launch.py
        slam_params_file:=/slam_params.yaml
        use_sim_time:=${USE_SIM_TIME:-False}

