# Quick Start
# $ docker compose -f compose.rosbot.yaml up

# x-net-config:
#   - &dds-config-file "./dds-config.xml:/dds-config.xml" 
#   - &dds-config-env "FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml"

x-net-config:
  - &network_mode "host" 
  - &restart_policy "unless-stopped"

services:

  dds-router:
    image: husarnet/dds-router:v0.4.0
    restart: *restart_policy
    network_mode: *network_mode
    ipc: *network_mode
    volumes:
      - ./router-config.client.yaml:/config.yaml
    command: >
      ddsrouter 
      --config-path /config.yaml 
      --debug

  rviz:
    image: husarion/rviz2:galactic
    container_name: rviz
    restart: *restart_policy
    network_mode: *network_mode
    ipc: *network_mode
    volumes:
      - ./robot_model:/robot_model
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot.rviz:/root/.rviz2/default.rviz
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=1

