# Quick Start
# $ docker compose -f compose.pc.yaml up

x-net-config:
  - &dds-config-file "./dds-config.xml:/dds-config.xml" 
  - &dds-config-env "FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml"

services:

  dds-router:
    image: husarnet/dds-router:v0.4.0
    restart: unless-stopped
    network_mode: host
    ipc: host
    volumes:
      - ./router-config.client.yaml:/config.yaml
    command: >
      ddsrouter 
      --config-path /config.yaml 
      --debug

  navigation:
    image: husarion/navigation2:galactic
    restart: unless-stopped
    network_mode: host
    ipc: host
    volumes:
      - ./config/nav2_params.yaml:/nav2_params.yaml
      # - *dds-config-file
    environment:
      # - *dds-config-env
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
    command: >
      ros2 launch nav2_bringup navigation_launch.py    
        params_file:=/nav2_params.yaml
        use_sim_time:=${USE_SIM_TIME:-False}

  localization-mapping:
    image: husarion/slam-toolbox:galactic
    restart: unless-stopped
    network_mode: host
    ipc: host
    container_name: slam-toolbox
    volumes:
      - ./config/slam_params.yaml:/slam_params.yaml
      - ./maps:/maps
      # - *dds-config-file
    environment:
      # - *dds-config-env
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
    command: >
      ros2 launch slam_toolbox online_sync_launch.py
        slam_params_file:=/slam_params.yaml
        use_sim_time:=${USE_SIM_TIME:-False}

  rviz:
    image: husarion/rviz2:galactic
    container_name: rviz
    restart: on-failure
    network_mode: host
    ipc: host
    volumes:
      - ./robot_model:/robot_model
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot.rviz:/root/.rviz2/default.rviz
      # - *dds-config-file
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=1
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
      # - *dds-config-env