# Quick Start
# $ docker compose -f compose.rosbot.yaml up

x-config: 
  - full-setup: &basic_setup
      restart: unless-stopped
      network_mode: host
      ipc: host
  - &restart_policy unless-stopped

services:

  dds-router:
    <<: *basic_setup
    image: husarnet/dds-router:v0.4.0
    volumes:
      - ./router-config.server.yaml:/config.yaml
    command: >
      ddsrouter 
      --config-path /config.yaml 
      --debug

  rplidar:
    <<: *basic_setup
    image: husarion/rplidar:galactic
    devices:
      - /dev/ttyUSB0
    command: >
      ros2 launch sllidar_ros2 sllidar_launch.py 
        serial_baudrate:=${RPLIDAR_BAUDRATE:-115200}

  bridge:
    image: husarion/ros:galactic-ros1-bridge
    restart: *restart_policy
    environment: 
      - ROS_MASTER_URI=http://ros-master:11311
    command: >
      ros2 run ros1_bridge dynamic_bridge

  ros-master:
    image: ros:noetic-ros-core
    restart: *restart_policy
    command: stdbuf -o L roscore

  rosbot:
    image: husarion/rosbot:noetic
    restart: *restart_policy
    devices:
      - ${SERIAL_PORT}
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
      - SERIAL_PORT=${SERIAL_PORT:?err}
    command: >
      roslaunch --wait rosbot_bringup rosbot_docker.launch

